# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0002_auto_20171125_0829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AequipoControlador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('puerto', models.IntegerField(default=8728)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AequipoControlador_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iAequipoControlador_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo controlador',
                'db_table': 'infraestructura_equipocontrolador',
            },
        ),
        migrations.CreateModel(
            name='BGrupoEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, default='logos/defaultGrupoEmpresarial.jpg', null=True, upload_to='logos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BGrupoEmpresarial_created_by', to=settings.AUTH_USER_MODEL)),
                ('equipoControlador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_grupoEmpresarial_equipoControlador', to='infraestructura.AequipoControlador')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BGrupoEmpresarial_modified_by', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_infraestructura_tipo', to='tipo.Tipo')),
                ('usuarios', models.ManyToManyField(related_name='fk_grupoempresarial_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que pueden ver las sedes del grupo empresarial')),
            ],
            options={
                'verbose_name': 'Grupo empresarial',
                'db_table': 'infraestructura_grupoempresarial',
            },
        ),
        migrations.CreateModel(
            name='CSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=150)),
                ('logoPropio', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, default='logos/defaultSede.jpg', null=True, upload_to='logos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSede_created_by', to=settings.AUTH_USER_MODEL)),
                ('grupoEmpresarial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_grupoempresarial_sede', to='infraestructura.BGrupoEmpresarial')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSede_modified_by', to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='fk_sede_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que pueden ver esta sede')),
            ],
            options={
                'verbose_name': 'Sede del grupo empresarial',
                'db_table': 'infraestructura_sede',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAequipoControlador',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('puerto', models.IntegerField(default=8728)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Equipo controlador',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBGrupoEmpresarial',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=150)),
                ('logo', models.TextField(blank=True, default='logos/defaultGrupoEmpresarial.jpg', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipoControlador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestructura.AequipoControlador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo.Tipo')),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Grupo empresarial',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCSede',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('nombre', models.CharField(max_length=150)),
                ('logoPropio', models.BooleanField(default=False)),
                ('logo', models.TextField(blank=True, default='logos/defaultSede.jpg', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grupoEmpresarial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestructura.BGrupoEmpresarial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Sede del grupo empresarial',
            },
        ),
        migrations.AlterUniqueTogether(
            name='csede',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='bgrupoempresarial',
            unique_together=set([('nombre', 'tipo')]),
        ),
        migrations.AlterUniqueTogether(
            name='aequipocontrolador',
            unique_together=set([('nombre',)]),
        ),
    ]
