# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0002_auto_20171125_0829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infraestructura', '0002_auto_20171201_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='APersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('0', '[Seleccione...]'), ('1', 'Masculino'), ('2', 'Femenino')], default=0, max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='APersona_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='APersona_modified_by', to=settings.AUTH_USER_MODEL)),
                ('tipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Persona_tipo', to='tipo.Tipo')),
            ],
            options={
                'verbose_name': 'Persona',
                'db_table': 'huesped_persona',
            },
        ),
        migrations.CreateModel(
            name='BHuesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('profesionOficio', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('hospedado', models.BooleanField()),
                ('acompananteDe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='huesped.BHuesped')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BHuesped_created_by', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_huesped_habitacion', to='infraestructura.DHabitacion')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BHuesped_modified_by', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_huesped_Persona', to='huesped.APersona')),
            ],
            options={
                'verbose_name': 'Huesped',
                'db_table': 'huesped_huesped',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAPersona',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('0', '[Seleccione...]'), ('1', 'Masculino'), ('2', 'Femenino')], default=0, max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipoIdentificacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tipo.Tipo')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Persona',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBHuesped',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualizacion')),
                ('profesionOficio', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('hospedado', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acompananteDe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='huesped.HistoricalBHuesped')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraestructura.DHabitacion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='huesped.APersona')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Huesped',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apersona',
            unique_together=set([('identificacion', 'tipoIdentificacion')]),
        ),
    ]
