# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhuesped',
            name='hospedado',
        ),
        migrations.RemoveField(
            model_name='historicalbhuesped',
            name='hospedado',
        ),
        migrations.AlterField(
            model_name='bhuesped',
            name='habitacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalbhuesped',
            name='habitacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
