# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0002_auto_20171205_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apersona',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apersona',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='bhuesped',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bhuesped',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalapersona',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalapersona',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalbhuesped',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalbhuesped',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='bhuesped',
            name='habitacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbhuesped',
            name='habitacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
